package-lock.json
package.json
src/styles/GlobalStyle.ts
src/styles/styled.d.ts
src/styles/theme.ts

POL-126 Feat: GlobalStyle

---

src/index.tsx
src/styles/GlobalStyle.ts
src/styles/theme.ts

Fix: Pol 134 global

---

src/containers/mentor-detail/mentor-detail.tsx
src/containers/signup/modal/info/info.tsx

Tag Array에러 수정했습니다.
조캉님 모달(login/info)에서 alert를 modal로 바꾸었습니다.

Pol 149 : 멘토상세페이지 

---

public/index.html
src/components/input-counterOnclicked.tsx
src/components/mentor-detail/button-box.tsx
src/components/mentor-detail/my-table.jsx
src/components/page-nation.tsx
src/containers/mentor-detail/mentor-detail.tsx

고쳐야할점 고쳤습니다.
추가로 문제점을 발견했습니다. inputBox에서 onChange로 setter가 반영이 되어서, edit을 눌러 작성후 취소버튼을 눌러도 이전으로 돌아가지 않습니다. 추후에 고치겠습니다.

Pol 149 : Fix

---

src/containers/mentor-detail/mentor-detail.tsx
src/containers/signup/mentor-info-modal.tsx
src/context/mentor-detail/mentor-detail-axios.ts

Pol 149 - 멘토 상세페이지

---

src/containers/mentor-detail/mentor-detail.tsx
src/states/auth/AuthStore.tsx

멘토가 join page를 거치지않고 왔을때 join page로 redirect 해주었습니다.
AuthStore의 join에 관한 interface와 function이 없어서 추가했습니다.
멘토에 의하여 멘토링 신청이 불가능할때 누르면 나오는 message를 수정했습니다.

Pol 149 : 멘토 상세페이지

---

src/components/mentor-detail/my-table.jsx
src/components/mentor-detail/select-keywords.tsx
src/containers/mentor-detail/mentor-detail.tsx

Pol 149 !HOTFIX

---

src/containers/signup/modal/info/info.tsx
src/containers/signup/modal/time/time.tsx
src/containers/signup/signup-mentor.tsx
src/containers/signup/signup-style.tsx

1. 슬랙 아이디 입력부분 좀 더 상세하게 수정
2. 가능 시간 입력 칸 위 아래 간격 줄임 -> 멘토 마이페이지 가능 시간 수정 부분

슬랙 아이디 입력부분 좀 더 상세하게 수정 등

---

src/containers/signup/signup-mentor.tsx

멘토 조인 페이지 feat: 소속, 직급 입력 추가

---

src/containers/cadet-mentoring/cadet-mentoring.tsx
src/containers/mentor-detail/mentor-detail.tsx

Fix:footer

---

src/states/my-mentoring-mentor/MentorLogStore.tsx
src/states/my-mentoring-mentor/MentorStore.tsx

Error 이유 test

---

src/components/header/header.tsx

Hotfix: 카뎃 로그인 다시 설정

---

src/containers/main-page/mainPageSilder.tsx

Fix:mobile Slider 순서

---

src/components/mentoring-log-card.tsx
src/containers/mentor-detail/mentor-detail.tsx
src/containers/reports/report-form.tsx
src/interface/mentor-detail/mentor-detail.interface.ts

Change : 인트라id -> 슬랙id
Delete : lefthook에서 안쓴다고 warning해주는것

Pol 149 : 멘토상세 페이지

---

src/containers/signup/signup-style.tsx

Fix: signup header

---

src/components/input-counter.tsx
src/containers/cadet-mentoring/modal/apply-detail-modal.tsx
src/containers/cadet-mentoring/modal/confirm/confirm.tsx
src/containers/cadet-mentoring/modal/modal.tsx
src/containers/reports/report-row-write.tsx
src/interfaces/cadet-mentoring/mentoring-log.interface.ts

카뎃 멘토링 로그 카드에 피드백 메시지 추가 & 거절 사유 디자인 변경

---

src/containers/reports/elements/report-fixable-with-modal.tsx
src/containers/reports/elements/report-time-picker/time-picker-modal.tsx
src/containers/reports/elements/report-time-picker/time-picker.tsx
src/containers/reports/report-form.tsx
src/states/repoort/ReportStore.tsx

Feat: 레포트 페이지 시간 수정 기능 구현

---

src/containers/mentor-detail/mentor-detail.tsx

Design: 멘토 상세페이지 모바일 css

---

src/containers/reports/report-row-signature.tsx

Feat: 드래그앤드랍 파일 업로드

---

src/components/footer.tsx

Fix: footer 문구 수정

---

src/components/footer.tsx
src/containers/report-detail/report-detail.tsx
src/containers/report-detail/reportStyled.tsx

<br/>
송피디님이 제시한 버그 리포트 수정의 일부분
- 카뎃이 여러명일 때 이름 여러명 들어갈 수 있게 수정
- 여러 페이지를 출력할 때 페이지가 점점 밀리는 거 수정
<br/>
버그 수정
<br/>
<br/>
<br/>

Fix: 보고서 여러 개 출력시 페이지가 밀리는 것 수정

---

src/containers/report-detail/report-detail.tsx
src/containers/report-detail/reportStyled.tsx

<br/>
보고서 일정 글씨 이상인 경우 폰트 조절
<br/>
- 칸을 넘어 문자가 적혀있는 일이 발생
<br/>
- 여러 경우의 글자를 두고 칸을 벗어나는지 테스트 함.
- 여러장의 페이지를 테스트함
- <br/>
<수정 된 사항>
1. 글자가 칸을 벗어나는 상황
2. 숫자로 임의적 넘김 대신 page-break-after를 이용함.
<테스트해봐야 하는 사항>
1. mac이나 다른 노트북에서도 밀림현상이 발생하지 않았는지 테스트 필요!
<br/>

Fix: report-detail 일정 글자 이상 폰트 조절 변경

---

package-lock.json
package.json
src/index.tsx
src/styles/GlobalStyle.ts
src/styles/styled.d.ts
src/styles/theme.ts
src/styles/themeV2.ts

Issues: #368
<br/>
- v1, v2 Global styled 1개로 합침
- v1, v2 Theme으로 2가지 default Theme을 가지게 수정
<br/>
기존 v2와 v1 레포를 1개로 합치려고 함
<br/>
로컬에서 스타일이 깨지는게 있는 지 확ㅇ딘함
<br/>
<br/>

feat: v1 Styles에 v2 Styles 추가 (feature/#368-Ver2-Styles) #368

---

src/components/footer.tsx

<br/>
1. Footer 모바일에서 글씨 깨지는 것 수정했습니다.
2. 글씨 크기를 1.3rem에서 1.2rem으로 변경했습니다.
<br/>
1. 깨지면 안 좋으니까요 ~
2. 1.3rem은 글씨가 내려가서 1.2로 변경했습니다 ~
<br/>
closes: #Issue Number
<br/>
<br/>

Fix : footer 모바일 깨짐 수정

---

package-lock.json
package.json
src/components/common/Providers.tsx
src/recoil/atoms/index.ts
src/recoil/atoms/modalAtom.ts
tsconfig.paths.json

<br/>
전역 상태 관리 라이브러리 `recoil` 적용합니다!
- https://github.com/42connected/polar-fe-v2/pull/54 
- 기존 작업 내역과 같으니 상기 풀리퀘 확인 바랍니다.
<br/>
<br/>
closes: #378 
<br/>
- `recoil` 관련 로직은 아직 추가하지 않았습니다.
- 기존 `MobX` 에서 점진적으로 변경 필요합니다.
<br/>

[Feature] recoil #378

---

src/components/v2/common/Button.tsx
src/components/v2/common/modal/ConfirmModal.tsx
src/components/v2/common/modal/DetailModal.tsx
src/components/v2/common/modal/ErrorModal.tsx
src/components/v2/common/modal/GuideModal.tsx
src/components/v2/common/modal/ModalBox.tsx
src/components/v2/common/modal/ModalInfoRow.tsx
src/components/v2/common/modal/ModalInputBox.tsx
src/components/v2/common/modal/StatusButton.tsx

<br/>
V2에서 컴포넌트 가져온 것들 최신화 작업했습니다.
<br/>
이전에 가져온 v2 컴포넌트들이 수정하기 이전의 컴포넌트들이어서, pull한 최신 상태의 컴포넌트들로 수정했습니다.
<br/>
closes: #Issue Number
메인페이지에 디테일 모달 버튼 추가해서 테스트해본 결과입니다!
<br/>
디테일 모달만 검사해본 상태이고, 다른 부분들은 면밀한 검사가 되지 않은 상태입니다! 추가적인 검사가 필요할 듯 싶고, 
스크린샷 우측의 warning은 수정 이전에도 발생했었습니다!
<br/>

Fix: componentV2 최신화 #369
